[build]
  # Build command
  command = "npm run build"
  
  # Directory to publish (where the built files are)
  publish = "dist"

[build.environment]
  # Node.js version
  NODE_VERSION = "18"

# Handle client-side routing (important for React apps)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Form handling for Netlify Forms
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

# Headers for better performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

